
scale_factor: 4.  # scaling factor for the game

# standard vi editor controls - do not change unless you know what you are doing
controls:
  dash-left: h
  dash-down: j
  dash-up: k
  dash-right: l

  blink-to-the-end-of-next-vegetation: e
  blink-to-the-end-of-next-vegetation-chunk: E
  blink-to-the-start-of-next-vegetation: w
  blink-to-the-start-of-next-vegetation-chunk: W
  blink-to-the-start-of-previous-vegetation: b
  blink-to-the-start-of-previous-vegetation-chunk: B

  blink-to-the-end-of-contour: '$'
  blink-to-the-start-of-contour: '0'
  blink-to-the-start-of-first-vegetation-chunk: '^'

  blink-to-the-top: 'gg'
  blink-up: 0x02
  blink-up-half: 0x15
  blink-down: 0x06
  blink-down-half: 0x04
  blink-to-the-bottom: G


buffer_keys: 'g'



